export const locations = [
    {
        title: 'Sydney',
        meta: {},
        items: [
            { title: 'Newtown', slug: 'newtown' },
            { title: 'Redfern', slug: 'redfern' },
            { title: 'Surry Hills', slug: 'surry-hills' },
            { title: 'Ultimo', slug: 'ultimo' },
            { title: 'Alexandria', slug: 'alexandria' },
            { title: 'Waterloo', slug: 'waterloo' },
            { title: 'Petersham', slug: 'petersham' },
            { title: 'Summer Hill', slug: 'summer-hill' },
            { title: 'Dulwich Hill', slug: 'dulwich-hill' },
            { title: 'Leichhardt', slug: 'leichhardt' },
            { title: 'Annandale', slug: 'annandale' },
            { title: 'Glebe', slug: 'glebe' },
            { title: 'Eveleigh', slug: 'eveleigh' },
            { title: 'Rosebery', slug: 'rosebery' },
            { title: 'Ashfield', slug: 'ashfield' },
            { title: 'Zetland', slug: 'zetland' },
            { title: 'Mascot', slug: 'mascot' },
            { title: 'Kensington', slug: 'kensington' },
            { title: 'Darlinghurst', slug: 'darlinghurst' },
            { title: 'Marrickville', slug: 'marrickville' },
            { title: 'Potts Point', slug: 'potts-point' },
            { title: 'Coogee', slug: 'coogee' },
            { title: 'Bondi', slug: 'bondi' },
            { title: 'Mosman', slug: 'mosman' },
            { title: 'Parramatta', slug: 'parramatta' },
            { title: 'Ryde', slug: 'ryde' },
            { title: 'Balmain', slug: 'balmain' },
            { title: 'Hornsby', slug: 'hornsby' },
            { title: 'North Sydeny', slug: 'north-sydney' },
            { title: 'Bronte', slug: 'bronte' },
            { title: 'Burwood', slug: 'burwood' },
            { title: 'Strathfield', slug: 'strathfield' },
        ],
    },
    {
        title: 'Melbourne',
        meta: {},
        items: [
            { title: 'St Kilda', slug: 'st-kilda' },
            { title: 'Brighton', slug: 'brighton' },
            { title: 'Southbank', slug: 'southbank' },
            { title: 'Abbotsford', slug: 'abbotsford' },
            { title: 'Brunswick', slug: 'brunswick' },
            { title: 'Carlton', slug: 'carlton' },
            { title: 'Coburg', slug: 'coburg' },
            { title: 'Collingwood', slug: 'collingwood' },
            { title: 'Craigieburn', slug: 'craigieburn' },
            { title: 'Footscary', slug: 'footscary' },
            { title: 'Docklands', slug: 'docklands' },
            { title: 'Elwood', slug: 'elwood' },
            { title: 'Essendon', slug: 'essendon' },
            { title: 'Hawthorn', slug: 'hawthorn' },
            { title: 'Kew', slug: 'kew' },
            { title: 'Pakenham', slug: 'pakenham' },
            { title: 'Prahran', slug: 'parahran' },
            { title: 'Reservoir', slug: 'reservoir' },
            { title: 'South Melbourne', slug: 'south-melbourne' },
            { title: 'Thornbury', slug: 'thornbury' },
        ],
    },
    {
        title: 'Brisbane',
        meta: {},
        items: [
            { title: 'Annerley', slug: 'annerley' },
            { title: 'Toowong', slug: 'toowong' },
            { title: 'Taringa', slug: 'taringa' },
            { title: 'Kelvin Grove', slug: 'kelvin-grove' },
            { title: 'East Brisbane', slug: 'east-brisbane' },
            { title: 'North Lakes', slug: 'north-lakes' },
            { title: 'Doolandella', slug: 'doolandella' },
            { title: 'Brendale', slug: 'brendale' },
            { title: 'Paddington', slug: 'paddington' },
            { title: 'Indooroopilly', slug: 'indooroopilly' },
            { title: 'St Lucia', slug: 'st-lucia' },
            { title: 'Fortitude Valley', slug: 'fortitude-valley' },
            { title: 'Woolloongabba', slug: 'woolloongabba' },
            { title: 'Newstead', slug: 'newstead' },
            { title: 'Greenslopes', slug: 'greenslopes' },
            { title: 'Upper Kedron', slug: 'upper-kedron' },
            { title: 'Mitchelton', slug: 'mitchelton' },
            { title: 'Chermside', slug: 'chermside' },
            { title: 'Morningside', slug: 'morningside' },
            { title: 'Nundah', slug: 'nundah' },
            { title: 'Coorparoo', slug: 'coorparoo' },
            { title: 'Kangaroo Point', slug: 'kangaroo-point' },
            { title: 'South Brisbane', slug: 'south-brisbane' },
            { title: 'New Farm', slug: 'new-farm' },
        ],
    },
    {
        title: 'Perth',
        meta: {},
        items: [
            { title: 'Ashfield', slug: 'ashfield' },
            { title: 'Bayswater', slug: 'bayswater' },
            { title: 'Beaconsfield', slug: 'beaconsfield' },
            { title: 'Bedford', slug: 'bedford' },
            { title: 'Como', slug: 'como' },
            { title: 'East Perth', slug: 'east-perth' },
            { title: 'Fremantle', slug: 'fremantle' },
            { title: 'Maylands', slug: 'maylands' },
            { title: 'Mosman Park', slug: 'mosman-park' },
            { title: 'Mount Lawley', slug: 'mount-lawley' },
            { title: 'Rivervale', slug: 'rivervale' },
            { title: 'Scarborough', slug: 'scarborough' },
            { title: 'South Perth', slug: 'south-perth' },
            { title: 'Subiaco', slug: 'subiaco' },
            { title: 'Success', slug: 'success' },
            { title: 'Thornlie', slug: 'thornlie' },
            { title: 'Tuart Hill', slug: 'tuart-hill' },
            { title: 'Victoria Park', slug: 'victoria-park' },
            { title: 'Wembley', slug: 'wembley' },
            { title: 'West Leederville', slug: 'west-leederville' },
        ],
    },
    {
        title: 'Canberra',
        meta: {},
        items: [
            { title: 'Barton', slug: 'barton' },
            { title: 'Bonner', slug: 'bonner' },
            { title: 'Braddon', slug: 'braddon' },
            { title: 'Bruce', slug: 'bruce' },
            { title: 'Calwell', slug: 'calwell' },
            { title: 'Campbell', slug: 'campbell' },
            { title: 'Crace', slug: 'crace' },
            { title: 'Forrest', slug: 'forrest' },
            { title: 'Franklin', slug: 'franklin' },
            { title: 'Greenway', slug: 'greenway' },
            { title: 'Griffith', slug: 'griffith' },
            { title: 'Harrison', slug: 'harrison' },
            { title: 'Kambah', slug: 'kambah' },
            { title: 'Kingston', slug: 'kingston' },
            { title: 'Lyneham', slug: 'lyneham' },
            { title: 'Macgregor', slug: 'macgregor' },
            { title: 'Ngunnawal', slug: 'ngunnawal' },
            { title: 'Phillip', slug: 'phillip' },
            { title: 'Turner', slug: 'turner' },
            { title: 'Watson', slug: 'watson' },
        ],
    },
];

export const cities = [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Canberra',
    'Gold Coast',
    'Adelaide',
];
