export const locations = [
    {
        title: 'Sydney',
        meta: {},
        items: [
            { title: 'Newtown', slug: 'newtown' },
            { title: 'Redfern', slug: 'redfern' },
            { title: 'Surry Hills', slug: 'surry-hills' },
            { title: 'Ultimo', slug: 'ultimo' },
            { title: 'Alexandria', slug: 'alexandria' },
            { title: 'Waterloo', slug: 'waterloo' },
            { title: 'Petersham', slug: 'petersham' },
            { title: 'Summer Hill', slug: 'summer-hill' },
            { title: 'Dulwich Hill', slug: 'dulwich-hill' },
            { title: 'Leichhardt', slug: 'leichhardt' },
            { title: 'Annandale', slug: 'annandale' },
            { title: 'Glebe', slug: 'glebe' },
            { title: 'Eveleigh', slug: 'eveleigh' },
            { title: 'Rosebery', slug: 'rosebery' },
            { title: 'Ashfield', slug: 'ashfield' },
            { title: 'Zetland', slug: 'zetland' },
            { title: 'Mascot', slug: 'mascot' },
            { title: 'Kensington', slug: 'kensington' },
            { title: 'Darlinghurst', slug: 'darlinghurst' },
            { title: 'Marrickville', slug: 'marrickville' },
            { title: 'Potts Point', slug: 'potts-point' },
            { title: 'Coogee', slug: 'coogee' },
            { title: 'Bondi', slug: 'bondi' },
            { title: 'Mosman', slug: 'mosman' },
            { title: 'Parramatta', slug: 'parramatta' },
            { title: 'Ryde', slug: 'ryde' },
            { title: 'Balmain', slug: 'balmain' },
            { title: 'Hornsby', slug: 'hornsby' },
            { title: 'North Sydeny', slug: 'north-sydney' },
            { title: 'Bronte', slug: 'bronte' },
            { title: 'Burwood', slug: 'burwood' },
            { title: 'Strathfield', slug: 'strathfield' },
        ],
    },
    {
        title: 'Melbourne',
        meta: {},
        items: [{ title: 'St Kilda', slug: 'st-kilda' }],
    },
];

export const cities = [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Canberra',
    'Gold Coast',
    'Adelaide',
];
