export const locations = [
    {
        title: 'Sydney',
        meta: {},
        items: [
            { title: 'Newtown', slug: 'newtown' },
            { title: 'Redfern', slug: 'redfern' },
            { title: 'Surry Hills', slug: 'surry-hills' },
            { title: 'Ultimo', slug: 'ultimo' },
            { title: 'Alexandria', slug: 'alexandria' },
            { title: 'Waterloo', slug: 'waterloo' },
            { title: 'Petersham', slug: 'petersham' },
            { title: 'Summer Hill', slug: 'summer-hill' },
            { title: 'Dulwich Hill', slug: 'dulwich-hill' },
            { title: 'Leichhardt', slug: 'leichhardt' },
            { title: 'Annandale', slug: 'annandale' },
            { title: 'Glebe', slug: 'glebe' },
            { title: 'Eveleigh', slug: 'eveleigh' },
            { title: 'Rosebery', slug: 'rosebery' },
            { title: 'Ashfield', slug: 'ashfield' },
            { title: 'Zetland', slug: 'zetland' },
            { title: 'Mascot', slug: 'mascot' },
            { title: 'Kensington', slug: 'kensington' },
            { title: 'Darlinghurst', slug: 'darlinghurst' },
            { title: 'Marrickville', slug: 'marrickville' },
            { title: 'Potts Point', slug: 'potts-point' },
            { title: 'Bondi Junction', slug: 'bondi-junction' },
            { title: 'Coogee', slug: 'coogee' },
            { title: 'South Coogee', slug: 'south-coogee' },
            { title: 'Bondi', slug: 'bondi' },
            { title: 'Little Bay', slug: 'little-bay' },
            { title: 'Malabar', slug: 'malabar' },
            { title: 'Bronte', slug: 'bronte' },
            { title: 'Clovelly', slug: 'clovelly' },
            { title: 'Waverley', slug: 'waverley' },
            { title: 'Randwick', slug: 'randwick' },
            { title: 'Kingsford', slug: 'kingsford' },
            { title: 'Rose Bay', slug: 'rose-bay' },
            { title: 'Double Bay', slug: 'double-bay' },
            { title: 'Maroubra', slug: 'maroubra' },
            { title: 'Chifley', slug: 'chifley' },
            { title: 'Ramsgate', slug: 'ramsgate' },
            { title: 'Rockdale', slug: 'rockdale' },
            { title: 'Chatswood', slug: 'chatswood' },
            { title: 'Neutral Bay', slug: 'neutral-bay' },
            { title: 'North Sydney', slug: 'north-sydney' },
            { title: 'Cremorne', slug: 'cremorne' },
            { title: 'Crows Nest', slug: 'crows-nest' },
            { title: 'St Leonards', slug: 'st-leonards' },
            { title: 'Mosman', slug: 'mosman' },
            { title: 'Parramatta', slug: 'parramatta' },
            { title: 'North Ryde', slug: 'north-ryde' },
            { title: 'Eastwood', slug: 'eastwood' },
            { title: 'Lindfield', slug: 'lindfield' },
            { title: 'Manly', slug: 'manly' },
            { title: 'Balgowlah', slug: 'balgowlah' },
            { title: 'Seaforth', slug: 'seaforth' },
            { title: 'Willoughby', slug: 'willoughby' },
            { title: 'Northbridge', slug: 'northbridge' },
            { title: 'Roseville', slug: 'roseville' },
            { title: 'Rhodes', slug: 'rhodes' },
            { title: 'Woolloomooloo', slug: 'woolloomooloo' },
            { title: 'Macquarie Park', slug: 'macquarie-park' },
            { title: 'Carlingford', slug: 'carlingford' },
            { title: 'Castle Hill', slug: 'castle-hill' },
            { title: 'Seven Hills', slug: 'seven-hills' },
            { title: 'Blacktown', slug: 'blacktown' },
            { title: 'Campbelltown', slug: 'campbelltown' },
            { title: 'Paddington', slug: 'paddington' },
            { title: 'Elizabeth Bay', slug: 'elizabeth-bay' },
            { title: 'Haymarket', slug: 'haymarket' },
            { title: 'Camperdown', slug: 'camperdown' },
            { title: 'Stanmore', slug: 'Stanmore' },
            { title: 'Five Dock', slug: 'five-dock' },
            { title: 'Haberfield', slug: 'haberfield' },
            { title: 'Lilyfield', slug: 'lilyfield' },
            { title: 'Rozelle', slug: 'rozelle' },
            { title: 'Balmain', slug: 'balmain' },
            { title: 'Birchgrove', slug: 'birchgrove' },
            { title: 'Balmain East', slug: 'balmain-east' },
            { title: 'Covelly', slug: 'covelly' },
            { title: 'Tamarama', slug: 'tamarama' },
            { title: 'Queens Park', slug: 'queens-park' },
            { title: 'North Bordi', slug: 'north-bondi' },
            { title: 'Rose Bay', slug: 'rose-bay' },
            { title: 'Vaucluse', slug: 'vaucluse' },
            { title: 'Eastlakes', slug: 'eastlakes' },
            { title: 'Pagewood', slug: 'pagewood' },
            { title: 'Batony', slug: 'botany' },
            { title: 'Hillsdale', slug: 'hillsdale' },
            { title: 'Matraville', slug: 'matraville' },
            { title: 'Chifley', slug: 'chifley' },
            { title: 'Malabar', slug: 'malabar' },
            { title: 'Beaconsfield', slug: 'beaconsfield' },
            { title: 'Tempe', slug: 'tempe' },
            { title: 'Wolli Creek', slug: 'wolli-creek' },
            { title: 'Turrella', slug: 'turrella' },
            { title: 'Kyeemagh', slug: 'kyeemagh' },
            { title: 'Banksia', slug: 'banksia' },
            { title: 'Ramsgate', slug: 'ramsgate' },
            { title: 'Sans Souci', slug: 'sans-souci' },
            { title: 'Sandringham', slug: 'sandringham' },
            { title: 'Cronulla', slug: 'cronulla' },
            { title: 'Woolooware', slug: 'woolooware' },
            { title: 'Burraneer', slug: 'burraneer' },
            { title: 'Caringbah', slug: 'caringbah' },
            { title: 'South Caringbah', slug: 'south-caringbah' },
            { title: 'Taren Point', slug: 'taren-point' },
            { title: 'Miranda', slug: 'miranda' },
            { title: 'Yowie Bay', slug: 'yowie-bay' },
            { title: 'Gymea Bay', slug: 'gymea-bay' },
            { title: 'Gymea', slug: 'gymea' },
            { title: 'Grays Point', slug: 'grays-point' },
            { title: 'Sutherland', slug: 'sutherland' },
            { title: 'Kirrawee', slug: 'kirrawee' },
            { title: 'Kangaroo Point', slug: 'kangaroo-point' },
            { title: 'Kareela', slug: 'kareela' },
            { title: 'Oyster Bay', slug: 'oyster-bay' },
            { title: 'Como', slug: 'como' },
            { title: 'Bonnet Bay', slug: 'bonnet-bay' },
            { title: 'Oately', slug: 'oately' },
            { title: 'Kyle Bay', slug: 'kyle-bay' },
            { title: 'Blakehurst', slug: 'blakehurst' },
            { title: 'Monterey', slug: 'monterey' },
            { title: 'Kogarah', slug: 'kogarah' },
            { title: 'Arncliffe', slug: 'arncliffe' },
            { title: 'Bexley', slug: 'bexley' },
            { title: 'Bexley North', slug: 'bexley-north' },
            { title: 'Turrella', slug: 'turrella' },
            { title: 'Bardwell Valley', slug: 'bardwell-valley' },
            { title: 'Bardwell Park', slug: 'bardwell-park' },
            { title: 'Bardwell Park', slug: 'bardwell-park' },
            { title: 'Earlwood', slug: 'earlwood' },
            { title: 'Kingsgrove', slug: 'kingsgrove' },
            { title: 'Clemton Park', slug: 'clemton-park' },
            { title: 'Roselands', slug: 'roselands' },
            { title: 'Canterbury', slug: 'canterbury' },
            { title: 'Riverwood', slug: 'riverwood' },
            { title: 'Peakhurst', slug: 'peakhurst' },
            { title: 'Mortdale', slug: 'mortdale' },
            { title: 'Lagarno', slug: 'lugarno' },
            { title: 'Padstow-heights', slug: 'padstow-heights' },
            { title: 'Padstow', slug: 'padstow' },
            { title: 'Revesby', slug: 'revesby' },
            { title: 'Panania', slug: 'Panania' },
            { title: 'Picnic Point', slug: 'picnic-point' },
            { title: 'Milperra', slug: 'milperra' },
            { title: 'Voyger Point', slug: 'voyger-point' },
            { title: 'Holsworthy', slug: 'holsworthy' },
            { title: 'Hammondville', slug: 'hammondville' },
            { title: 'Wattle Grove', slug: 'wattle-grove' },
            { title: 'Moorebank', slug: 'moorebank' },
            { title: 'Liverpool', slug: 'liverpool' },
            { title: 'Casula', slug: 'casula' },
            { title: 'Glenfield', slug: 'glenfield' },
            { title: 'Macquarie Fields', slug: 'macquarie-fields' },
            { title: 'Ingleburn', slug: 'ingleburn' },
            { title: 'Minto', slug: 'minto' },
            { title: 'Ruse', slug: 'ruse' },
            { title: 'Airds', slug: 'airds' },
            { title: 'Bradbury', slug: 'bradbury' },
            { title: 'St Helens Park', slug: 'st-helens-park' },
            { title: 'Rosemeadow', slug: 'rosemeadow' },
            { title: 'Ambarvale', slug: 'ambarvale' },
            { title: 'Glen Alpine', slug: 'glen-alpine' },
            { title: 'Englorie Park', slug: 'englorie-park' },
            { title: 'Blair Athol', slug: 'blair-athol' },
            { title: 'Beumeah', slug: 'beumeah' },
            { title: 'Woodbine', slug: 'woodbine' },
            { title: 'Blairmount', slug: 'blairmount' },
            { title: 'Claymore', slug: 'claymore' },
            { title: 'Eagle Vale', slug: 'eagle-vale' },
            { title: 'Eschol Park', slug: 'eschol-park' },
            { title: 'Kearns', slug: 'kearns' },
            { title: 'Raby', slug: 'raby' },
            { title: 'St Andrews', slug: 'st-andrews' },
            { title: 'Bardia', slug: 'bardia' },
            { title: 'Macquire Links', slug: 'macquire-links' },
            { title: 'Edmondson Park', slug: 'edmondson-park' },
            { title: 'Prestons', slug: 'prestons' },
            { title: 'Hoxton Park', slug: 'hoxton-park' },
            { title: 'Horningsea Park', slug: 'horningsea-park' },
            { title: 'Concord West', slug: 'concord-west' },
            { title: 'Concord', slug: 'concord' },
            { title: 'Burwood', slug: 'burwood' },
            { title: 'Rodd Point', slug: 'rood-point' },
            { title: 'Russell Lea', slug: 'russell-lea' },
            { title: 'Brichgrove', slug: 'brichgrove' },
            { title: 'Drummoyne', slug: 'drummoyne' },
            { title: 'Wareemba', slug: 'wareemba' },
            { title: 'Abbotsford', slug: 'abbotsford' },
            { title: 'Chiswick', slug: 'chiswick' },
            { title: 'Canada Bay', slug: 'canada-bay' },
            { title: 'Strathfield', slug: 'strathfield' },
            { title: 'North Strathfield', slug: 'north-strathfield' },
            { title: 'Strathfield South', slug: 'strathfield-south' },
            { title: 'Concord', slug: 'concord' },
            { title: 'Cabarita', slug: 'cabarita' },
            { title: 'Breakfast Point', slug: 'breakfast-point' },
            { title: 'Mortlake', slug: 'mortlake' },
            { title: 'Concord West', slug: 'concord-west' },
            { title: 'Liberty Grove', slug: 'liberty-grove' },
            { title: 'Rhodes', slug: 'rhodes' },
            { title: 'Wentworth Point', slug: 'wentworth-point' },
            {
                title: 'Sydney Olympic Park',
                slug: 'sydney-olympic-park',
            },
            {
                title: 'Newington',
                slug: 'newington',
            },
            {
                title: 'Silverwater',
                slug: 'silverwater',
            },
            {
                title: 'Enfield',
                slug: 'enfield',
            },
            {
                title: 'Burwood Heights',
                slug: 'burwood-heights',
            },
            {
                title: 'Ashbury',
                slug: 'ashbury',
            },
            { title: 'Croydon', slug: 'croydon' },
            { title: 'Croydon Park', slug: 'croydon-park' },
            { title: 'Ashbury', slug: 'ashbury' },
            { title: 'Lewisham', slug: 'lewisham' },
            { title: 'Homebush', slug: 'homebush' },
            { title: 'Lidcome', slug: 'lidcome' },
            { title: 'Greenwich', slug: 'greenwich' },
            { title: 'Northwood', slug: 'northwood' },
            { title: 'Cammeray', slug: 'cammeray' },
            { title: 'Kurraba Point', slug: 'kurraba-point' },
            { title: 'Cremorne Point', slug: 'cremorne-point' },
            { title: 'Lane Cove', slug: 'lane-cove' },
            { title: 'Longueville', slug: 'longueville' },
            { title: 'Riverview', slug: 'riverview' },
            { title: 'Linley Point', slug: 'linley-point' },
            { title: 'Lane Cove West', slug: 'lane-cove-west' },
            { title: 'Lane Cove North', slug: 'lane-cove-north' },
            { title: 'Artarmon', slug: 'artarmon' },
            { title: 'Castlecrag', slug: 'castlecrag' },
            { title: 'Middle Cove', slug: 'middle-cove' },
            { title: 'Castle Cove', slug: 'castle-cove' },
            { title: 'Roseville Chase', slug: 'roseville-chase' },
            { title: 'Chatswood West', slug: 'chatswood-west' },
            { title: 'East Lindfield', slug: 'east-lindfield' },
            { title: 'Killara', slug: 'killara' },
            { title: 'East Killara', slug: 'east-killara' },
            { title: 'Gordon', slug: 'gordon' },
            { title: 'Pymble', slug: 'pymble' },
            { title: 'West Pymble', slug: 'west-pymble' },
            { title: 'Turramurra', slug: 'turramurra' },
            { title: 'South Turramurra', slug: 'south-turramurra' },
            { title: 'North Turramurra', slug: 'north-turramurra' },
            { title: 'St. Leves', slug: 'st-leves' },
            { title: 'St. Leves Chase', slug: 'st-leves-chase' },
            { title: 'Warrawee', slug: 'warrawee' },
            { title: 'Wahroonga', slug: 'wahroonga' },
            { title: 'North Wahroonga', slug: 'north-wahroonga' },
            { title: 'Waitara', slug: 'waitara' },
            { title: 'Hornsby', slug: 'hornsby' },
            { title: 'Asquith', slug: 'asquith' },
            { title: 'Normanhurst', slug: 'normanhurst' },
            { title: 'Thornleight', slug: 'thornleigh' },
            { title: 'Westleigh', slug: 'westleigh' },
            { title: 'Pennant Hills', slug: 'pennant-hills' },
            { title: 'Beecroft', slug: 'beecroft' },
            { title: 'Cheltenham', slug: 'Cheltenham' },
            { title: 'Epping', slug: 'epping' },
            { title: 'North Epping', slug: 'north-epping' },
            { title: 'Eastwood', slug: 'eastwood' },
            { title: 'Marsfield', slug: 'marsfield' },
            { title: 'Maquire Park', slug: 'maquire-park' },
            { title: 'Denistone', slug: 'denistone' },
            { title: 'Denistone East', slug: 'denistone-east' },
            { title: 'Denistone West', slug: 'denistone-west' },
            { title: 'Meadowbank', slug: 'meadowbank' },
            { title: 'Putney', slug: 'putney' },
            { title: 'Tunnyson Point', slug: 'tennyson-point' },
            { title: 'Gladsville', slug: 'gladsville' },
            { title: 'Henley', slug: 'henley' },
            { title: 'Huntleys Cove', slug: 'huntleys-cove' },
            { title: 'Henley', slug: 'henley' },
            { title: 'Huntleys Point', slug: 'huntleys-point' },
            { title: 'Huntleys Cove', slug: 'huntleys-cove' },
            { title: 'Hunters Hill', slug: 'hunters-hill' },
            { title: 'Ryde', slug: 'ryde' },
            { title: 'East Ryde', slug: 'east-ryde' },
            { title: 'North Ryde', slug: 'north-ryde' },
            { title: 'Macdonaldtown', slug: 'macdonaldtown' },
            { title: 'Erskineville', slug: 'erskineville' },
            { title: 'St Peters', slug: 'st-peters' },
            { title: 'Sydenham', slug: 'sydenham' },
            { title: 'Dover Heights', slug: 'dover-heights' },
            { title: 'Watsons Bay', slug: 'watsons-bay' },
            { title: 'Kings Cross', slug: 'kings-cross' },
            { title: 'Woollahra', slug: 'woollahra' },
            { title: 'Centennial Park', slug: 'centennial-park' },
            { title: 'Queens Park', slug: 'queens-park' },
            { title: 'Phillip Bay', slug: 'phillip-bay' },
            { title: 'Eastgardens', slug: 'eastgardens' },
            { title: 'Banksmeadow', slug: 'banksmeadow' },
            { title: 'Hillsdale', slug: 'hillsdale' },
            { title: 'Moore Park', slug: 'moore-park' },
            { title: 'Enmore', slug: 'enmore' },
            { title: 'Melrose Park', slug: 'melrose-park' },
            { title: 'Ermington', slug: 'ermington' },
            { title: 'Rydalmere', slug: 'rydalmere' },
            { title: 'Rosehill', slug: 'rosehill' },
            { title: 'Camellia', slug: 'camellia' },
            { title: 'Clyde', slug: 'clyde' },
            { title: 'Granville', slug: 'granville' },
            { title: 'Harris Park', slug: 'harris-park' },
            { title: 'North Parramatta', slug: 'north-parramatta' },
            { title: 'Westmead', slug: 'westmead' },
            { title: 'Dundas', slug: 'dundas' },
            { title: 'Telopea', slug: 'telopea' },
            { title: 'Dundas Valley', slug: 'dundas-valley' },
            { title: 'Oatlands', slug: 'oatlands' },
            { title: 'Carlingfords', slug: 'carlingford' },
            { title: 'West Pennant Hills', slug: 'west-pennant-hills' },
            { title: 'Pennant Hills', slug: 'pennant-hills' },
            { title: 'Cherrybrook', slug: 'cherrybrook' },
            { title: 'North Rocks', slug: 'north-rocks' },
            { title: 'Northmead', slug: 'northmead' },
            { title: 'Castle Hill', slug: 'castle-hill' },
            { title: 'Baulkham Hills', slug: 'baulkham-hills' },
            { title: 'Kellyville', slug: 'kellyville' },
            { title: 'Norwest', slug: 'norwest' },
            { title: 'Bella Vista', slug: 'bella-vista' },
            { title: 'Quakers Hill', slug: 'quakers-hill' },
            { title: 'Toongabbie', slug: 'toongabbie' },
            { title: 'Balgowlah Heights', slug: 'balgowlah-heights' },
            { title: 'Clontarf', slug: 'clontarf' },
            { title: 'North Balgowlah', slug: 'north-balgowlah' },
            { title: 'Manly Vale', slug: 'manly-vale' },
            { title: 'Fairlight', slug: 'fairlight' },
            { title: 'Queenscliff', slug: 'queenscliff' },
            { title: 'Freshwater', slug: 'freshwater' },
            { title: 'North Manly', slug: 'north-manly' },
            { title: 'Brookvale', slug: 'brookvale' },
            { title: 'North Curl Curl', slug: 'north-curl-curl' },
            { title: 'Dee Why', slug: 'dee-why' },
            { title: 'Narraweena', slug: 'narraweena' },
            { title: 'Allambie Heights', slug: 'allambie-heights' },
            { title: 'Beacon Hill', slug: 'beacon-hill' },
            { title: 'Frenchs Forest', slug: 'frenchs-forest' },
            { title: 'Cromer', slug: 'cromer' },
        ],
    },
    {
        title: 'Melbourne',
        meta: {},
        items: [
            { title: 'Abbotsford VIC', slug: 'abbotsford' },
            { title: 'Aberfeldie', slug: 'aberfeldie' },
            { title: 'Albanvale', slug: 'albanvale' },
            { title: 'Albert Park VIC', slug: 'albert-park' },
            { title: 'Albion VIC', slug: 'albion' },
            { title: 'Alphington', slug: 'alphington' },
            { title: 'Altona', slug: 'altona' },
            { title: 'Altona Meadows', slug: 'altona-meadows' },
            { title: 'Altona North', slug: 'altona-north' },
            { title: 'Ardeer', slug: 'ardeer' },
            { title: 'Armadale VIC', slug: 'armadale' },
            { title: 'Ascot Vale', slug: 'ascot-vale' },
            { title: 'Ashburton', slug: 'ashburton' },
            { title: 'Ashwood', slug: 'ashwood' },
            { title: 'Aspendale', slug: 'aspendale' },
            { title: 'Aspendale Gardens', slug: 'aspendale-gardens' },
            { title: 'Attwood', slug: 'attwood' },
            { title: 'Avondale Heights', slug: 'avondale-heights' },
            { title: 'Avonsleigh', slug: 'avonsleigh' },
            { title: 'Balaclava', slug: 'balaclava' },
            { title: 'Balwyn', slug: 'balwyn' },
            { title: 'Balwyn North', slug: 'balwyn-north' },
            { title: 'Bangholme', slug: 'bangholme' },
            { title: 'Baxter', slug: 'baxter' },
            { title: 'Bayswater North', slug: 'bayswater-north' },
            { title: 'Bayswater VIC', slug: 'bayswater' },
            { title: 'Beaconsfield VIC', slug: 'beaconsfield' },
            { title: 'Beaumaris', slug: 'beaumaris' },
            { title: 'Belgrave', slug: 'belgrave' },
            { title: 'Belgrave Heights', slug: 'belgrave-heights' },
            { title: 'Belgrave South', slug: 'belgrave-south' },
            { title: 'Bellfield', slug: 'bellfield' },
            { title: 'Bentleigh', slug: 'bentleigh' },
            { title: 'Bentleigh East', slug: 'bentleigh-east' },
            { title: 'Berwick', slug: 'berwick' },
            { title: 'Bittern', slug: 'bittern' },
            { title: 'Black Rock', slug: 'black-rock' },
            { title: 'Blackburn', slug: 'blackburn' },
            { title: 'Blackburn North', slug: 'blackburn-north' },
            { title: 'Blackburn South', slug: 'blackburn-south' },
            { title: 'Blairgowrie', slug: 'blairgowrie' },
            { title: 'Bonbeach', slug: 'bonbeach' },
            { title: 'Boronia', slug: 'boronia' },
            { title: 'Botanic Ridge', slug: 'botanic-ridge' },
            { title: 'Box Hill', slug: 'box-hill' },
            { title: 'Box Hill North', slug: 'box-hill-north' },
            { title: 'Box Hill South', slug: 'box-hill-south' },
            { title: 'Braeside', slug: 'braeside' },
            { title: 'Braybrook', slug: 'braybrook' },
            { title: 'Briar Hill', slug: 'briar-hill' },
            { title: 'Brighton East', slug: 'brighton-east' },
            { title: 'Brighton VIC', slug: 'brighton' },
            { title: 'Broadmeadows', slug: 'broadmeadows' },
            { title: 'Brooklyn', slug: 'brooklyn' },
            { title: 'Brunswick', slug: 'brunswick' },
            { title: 'Brunswick East', slug: 'brunswick-east' },
            { title: 'Brunswick West', slug: 'brunswick-west' },
            { title: 'Bulleen', slug: 'bulleen' },
            { title: 'Bundoora', slug: 'bundoora' },
            { title: 'Burnley', slug: 'burnley' },
            { title: 'Burnside Heights', slug: 'burnside-heights' },
            { title: 'Burnside VIC', slug: 'burnside' },
            { title: 'Burwood East', slug: 'burwood-east' },
            { title: 'Burwood VIC', slug: 'burwood' },
            { title: 'Cairnlea', slug: 'cairnlea' },
            { title: 'Calder Park', slug: 'calder-park' },
            { title: 'Camberwell', slug: 'camberwell' },
            { title: 'Campbellfield', slug: 'campbellfield' },
            { title: 'Canterbury VIC', slug: 'canterbury' },
            { title: 'Carlton North', slug: 'carlton-north' },
            { title: 'Carlton VIC', slug: 'carlton' },
            { title: 'Carnegie', slug: 'carnegie' },
            { title: 'Caroline Springs', slug: 'caroline-springs' },
            { title: 'Carrum', slug: 'carrum' },
            { title: 'Carrum Downs', slug: 'carrum-downs' },
            { title: 'Caulfield', slug: 'caulfield' },
            { title: 'Caulfield East', slug: 'caulfield-east' },
            { title: 'Caulfield North', slug: 'caulfield-north' },
            { title: 'Caulfield South', slug: 'caulfield-south' },
            { title: 'Chadstone', slug: 'chadstone' },
            { title: 'Chelsea', slug: 'chelsea' },
            { title: 'Chelsea Heights', slug: 'chelsea-heights' },
            { title: 'Cheltenham VIC', slug: 'cheltenham' },
            { title: 'Chirnside Park', slug: 'chirnside-park' },
            { title: 'Clarinda', slug: 'clarinda' },
            { title: 'Clayton', slug: 'clayton' },
            { title: 'Clayton South', slug: 'clayton-south' },
            { title: 'Clematis', slug: 'clematis' },
            { title: 'Clifton Hill', slug: 'clifton-hill' },
            { title: 'Clyde North', slug: 'clyde-north' },
            { title: 'Coburg', slug: 'coburg' },
            { title: 'Coburg North', slug: 'coburg-north' },
            { title: 'Cockatoo', slug: 'cockatoo' },
            { title: 'Coldstream', slug: 'coldstream' },
            { title: 'Collingwood', slug: 'collingwood' },
            { title: 'Coolaroo', slug: 'coolaroo' },
            { title: 'Craigieburn', slug: 'craigieburn' },
            { title: 'Cranbourne', slug: 'cranbourne' },
            { title: 'Cranbourne East', slug: 'cranbourne-east' },
            { title: 'Cranbourne North', slug: 'cranbourne-north' },
            { title: 'Cranbourne South', slug: 'cranbourne-south' },
            { title: 'Cranbourne West', slug: 'cranbourne-west' },
            { title: 'Cremorne VIC', slug: 'cremorne' },
            { title: 'Crib Point', slug: 'crib-point' },
            { title: 'Croydon Hills', slug: 'croydon-hills' },
            { title: 'Croydon North', slug: 'croydon-north' },
            { title: 'Croydon South', slug: 'croydon-south' },
            { title: 'Croydon VIC', slug: 'croydon' },
            { title: 'Dallas', slug: 'dallas' },
            { title: 'Dandenong', slug: 'dandenong' },
            { title: 'Dandenong North', slug: 'dandenong-north' },
            { title: 'Dandenong South', slug: 'dandenong-south' },
            { title: 'Deepdene', slug: 'deepdene' },
            { title: 'Deer Park', slug: 'deer-park' },
            { title: 'Delahey', slug: 'delahey' },
            { title: 'Derrimut', slug: 'derrimut' },
            { title: 'Diamond Creek', slug: 'diamond-creek' },
            { title: 'Dingley Village', slug: 'dingley-village' },
            { title: 'Docklands', slug: 'docklands' },
            { title: 'Doncaster', slug: 'doncaster' },
            { title: 'Doncaster East', slug: 'doncaster-east' },
            { title: 'Donvale', slug: 'donvale' },
            { title: 'Doveton', slug: 'doveton' },
            { title: 'Dromana', slug: 'dromana' },
            { title: 'Eaglemont', slug: 'eaglemont' },
            { title: 'East Melbourne', slug: 'east-melbourne' },
            { title: 'Edithvale', slug: 'edithvale' },
            { title: 'Elsternwick', slug: 'elsternwick' },
            { title: 'Eltham', slug: 'eltham' },
            { title: 'Eltham North', slug: 'eltham-north' },
            { title: 'Elwood', slug: 'elwood' },
            { title: 'Emerald', slug: 'emerald' },
            { title: 'Endeavour Hills', slug: 'endeavour-hills' },
            { title: 'Epping VIC', slug: 'epping' },
            { title: 'Essendon', slug: 'essendon' },
            { title: 'Essendon Fields', slug: 'essendon-fields' },
            { title: 'Essendon North', slug: 'essendon-north' },
            { title: 'Essendon West', slug: 'essendon-west' },
            { title: 'Eumemmerring', slug: 'eumemmerring' },
            { title: 'Fairfield VIC', slug: 'fairfield' },
            { title: 'Fawkner', slug: 'fawkner' },
            { title: 'Ferntree Gully', slug: 'ferntree-gully' },
            { title: 'Ferny Creek', slug: 'ferny-creek' },
            { title: 'Fitzroy North', slug: 'fitzroy-north' },
            { title: 'Fitzroy VIC', slug: 'fitzroy' },
            { title: 'Flemington', slug: 'flemington' },
            { title: 'Footscray', slug: 'footscray' },
            { title: 'Forest Hill', slug: 'forest-hill' },
            { title: 'Frankston', slug: 'frankston' },
            { title: 'Frankston North', slug: 'frankston-north' },
            { title: 'Frankston South', slug: 'frankston-south' },
            { title: 'Gardenvale', slug: 'gardenvale' },
            { title: 'Gladstone Park', slug: 'gladstone-park' },
            { title: 'Glen Huntly', slug: 'glen-huntly' },
            { title: 'Glen Iris', slug: 'glen-iris' },
            { title: 'Glen Waverley', slug: 'glen-waverley' },
            { title: 'Glenroy', slug: 'glenroy' },
            { title: 'Gowanbrae', slug: 'gowanbrae' },
            { title: 'Greensborough', slug: 'greensborough' },
            { title: 'Greenvale', slug: 'greenvale' },
            { title: 'Hadfield', slug: 'hadfield' },
            { title: 'Hallam', slug: 'hallam' },
            { title: 'Hampton', slug: 'hampton' },
            { title: 'Hampton East', slug: 'hampton-east' },
            { title: 'Hampton Park', slug: 'hampton-park' },
            { title: 'Harkaway', slug: 'harkaway' },
            { title: 'Hastings', slug: 'hastings' },
            { title: 'Hawthorn East', slug: 'hawthorn-east' },
            { title: 'Hawthorn VIC', slug: 'hawthorn' },
            { title: 'Heatherton', slug: 'heatherton' },
            { title: 'Heathmont', slug: 'heathmont' },
            { title: 'Heidelberg', slug: 'heidelberg' },
            { title: 'Heidelberg Heights', slug: 'heidelberg-heights' },
            { title: 'Heidelberg West', slug: 'heidelberg-west' },
            { title: 'Highett', slug: 'highett' },
            { title: 'Hillside', slug: 'hillside' },
            { title: 'Hmas Cerberus', slug: 'hmas-cerberus' },
            { title: 'Hoppers Crossing', slug: 'hoppers-crossing' },
            { title: 'Hughesdale', slug: 'hughesdale' },
            { title: 'Huntingdale VIC', slug: 'huntingdale' },
            { title: 'Hurstbridge', slug: 'hurstbridge' },
            { title: 'Ivanhoe', slug: 'ivanhoe' },
            { title: 'Ivanhoe East', slug: 'ivanhoe-east' },
            { title: 'Jacana', slug: 'jacana' },
            { title: 'Junction Village', slug: 'junction-village' },
            { title: 'Kalkallo', slug: 'kalkallo' },
            { title: 'Kallista', slug: 'kallista' },
            { title: 'Kalorama', slug: 'kalorama' },
            { title: 'Kealba', slug: 'kealba' },
            { title: 'Keilor', slug: 'keilor' },
            { title: 'Keilor Downs', slug: 'keilor-downs' },
            { title: 'Keilor East', slug: 'keilor-east' },
            { title: 'Keilor Lodge', slug: 'keilor-lodge' },
            { title: 'Keilor North', slug: 'keilor-north' },
            { title: 'Keilor Park', slug: 'keilor-park' },
            { title: 'Kensington VIC', slug: 'kensington' },
            { title: 'Kew', slug: 'kew' },
            { title: 'Kew East', slug: 'kew-east' },
            { title: 'Keysborough', slug: 'keysborough' },
            { title: 'Kilsyth', slug: 'kilsyth' },
            { title: 'Kilsyth South', slug: 'kilsyth-south' },
            { title: 'Kings Park VIC', slug: 'kings-park' },
            { title: 'Kingsbury', slug: 'kingsbury' },
            { title: 'Kingsville', slug: 'kingsville' },
            { title: 'Knoxfield', slug: 'knoxfield' },
            { title: 'Kooyong', slug: 'kooyong' },
            { title: 'Lalor', slug: 'lalor' },
            { title: 'Langwarrin', slug: 'langwarrin' },
            { title: 'Langwarrin South', slug: 'langwarrin-south' },
            { title: 'Laverton', slug: 'laverton' },
            { title: 'Laverton North', slug: 'laverton-north' },
            { title: 'Lilydale', slug: 'lilydale' },
            { title: 'Lower Plenty', slug: 'lower-plenty' },
            { title: 'Lynbrook', slug: 'lynbrook' },
            { title: 'Lyndhurst', slug: 'lyndhurst' },
            { title: 'Lysterfield', slug: 'lysterfield' },
            { title: 'Lysterfield South', slug: 'lysterfield-south' },
            { title: 'Macleod', slug: 'macleod' },
            { title: 'Maidstone', slug: 'maidstone' },
            { title: 'Malvern East', slug: 'malvern-east' },
            { title: 'Malvern VIC', slug: 'malvern' },
            { title: 'Maribyrnong', slug: 'maribyrnong' },
            { title: 'McCrae', slug: 'mccrae' },
            { title: 'McKinnon', slug: 'mckinnon' },
            { title: 'Meadow Heights', slug: 'meadow-heights' },
            { title: 'Mentone', slug: 'mentone' },
            { title: 'Menzies Creek', slug: 'menzies-creek' },
            { title: 'Mernda', slug: 'mernda' },
            { title: 'Middle Park VIC', slug: 'middle-park' },
            { title: 'Mill Park', slug: 'mill-park' },
            { title: 'Mitcham VIC', slug: 'mitcham' },
            { title: 'Monbulk', slug: 'monbulk' },
            { title: 'Mont Albert', slug: 'mont-albert' },
            { title: 'Mont Albert North', slug: 'mont-albert-north' },
            { title: 'Montmorency', slug: 'montmorency' },
            { title: 'Montrose VIC', slug: 'montrose' },
            { title: 'Moonee Ponds', slug: 'moonee-ponds' },
            { title: 'Moorabbin', slug: 'moorabbin' },
            { title: 'Mooroolbark', slug: 'mooroolbark' },
            { title: 'Mordialloc', slug: 'mordialloc' },
            { title: 'Mornington VIC', slug: 'mornington' },
            { title: 'Mount Dandenong', slug: 'mount-dandenong' },
            { title: 'Mount Eliza', slug: 'mount-eliza' },
            { title: 'Mount Evelyn', slug: 'mount-evelyn' },
            { title: 'Mount Martha', slug: 'mount-martha' },
            { title: 'Mount Waverley', slug: 'mount-waverley' },
            { title: 'Mulgrave VIC', slug: 'mulgrave' },
            { title: 'Murrumbeena', slug: 'murrumbeena' },
            { title: 'Narre Warren', slug: 'narre-warren' },
            { title: 'Narre Warren North', slug: 'narre-warren-north' },
            { title: 'Narre Warren South', slug: 'narre-warren-south' },
            { title: 'Newport VIC', slug: 'newport' },
            { title: 'Niddrie', slug: 'niddrie' },
            { title: 'Noble Park', slug: 'noble-park' },
            { title: 'Noble Park North', slug: 'noble-park-north' },
            { title: 'North Melbourne', slug: 'north-melbourne' },
            { title: 'North Warrandyte', slug: 'north-warrandyte' },
            { title: 'Northcote', slug: 'northcote' },
            { title: 'Notting Hill', slug: 'notting-hill' },
            { title: 'Nunawading', slug: 'nunawading' },
            { title: 'Oak Park', slug: 'oak-park' },
            { title: 'Oaklands Junction', slug: 'oaklands-junction' },
            { title: 'Oakleigh', slug: 'oakleigh' },
            { title: 'Oakleigh East', slug: 'oakleigh-east' },
            { title: 'Oakleigh South', slug: 'oakleigh-south' },
            { title: 'Officer', slug: 'officer' },
            { title: 'Olinda', slug: 'olinda' },
            { title: 'Ormond', slug: 'ormond' },
            { title: 'Pakenham', slug: 'pakenham' },
            { title: 'Park Orchards', slug: 'park-orchards' },
            { title: 'Parkdale', slug: 'parkdale' },
            { title: 'Parkville', slug: 'parkville' },
            { title: 'Pascoe Vale', slug: 'pascoe-vale' },
            { title: 'Pascoe Vale South', slug: 'pascoe-vale-south' },
            { title: 'Patterson Lakes', slug: 'patterson-lakes' },
            { title: 'Pearcedale', slug: 'pearcedale' },
            { title: 'Point Cook', slug: 'point-cook' },
            { title: 'Port Melbourne', slug: 'port-melbourne' },
            { title: 'Portsea', slug: 'portsea' },
            { title: 'Prahran', slug: 'prahran' },
            { title: 'Preston', slug: 'preston' },
            { title: 'Princes Hill', slug: 'princes-hill' },
            { title: 'Research', slug: 'research' },
            { title: 'Reservoir', slug: 'reservoir' },
            { title: 'Richmond VIC', slug: 'richmond' },
            { title: 'Ringwood', slug: 'ringwood' },
            { title: 'Ringwood East', slug: 'ringwood-east' },
            { title: 'Ringwood North', slug: 'ringwood-north' },
            { title: 'Ripponlea', slug: 'ripponlea' },
            { title: 'Rosanna', slug: 'rosanna' },
            { title: 'Rosebud', slug: 'rosebud' },
            { title: 'Rosebud West', slug: 'rosebud-west' },
            { title: 'Rowville', slug: 'rowville' },
            { title: 'Roxburgh Park', slug: 'roxburgh-park' },
            { title: 'Rye', slug: 'rye' },
            { title: 'Safety Beach', slug: 'safety-beach' },
            { title: 'Sandhurst', slug: 'sandhurst' },
            { title: 'Sandringham VIC', slug: 'sandringham' },
            { title: 'Sassafras', slug: 'sassafras' },
            { title: 'Scoresby', slug: 'scoresby' },
            { title: 'Seabrook', slug: 'seabrook' },
            { title: 'Seaford VIC', slug: 'seaford' },
            { title: 'Seaholme', slug: 'seaholme' },
            { title: 'Seddon', slug: 'seddon' },
            { title: 'Selby', slug: 'selby' },
            { title: 'Sherbrooke', slug: 'sherbrooke' },
            { title: 'Skye VIC', slug: 'skye' },
            { title: 'Somers', slug: 'somers' },
            { title: 'Somerton', slug: 'somerton' },
            { title: 'Somerville', slug: 'somerville' },
            { title: 'Sorrento VIC', slug: 'sorrento' },
            { title: 'South Kingsville', slug: 'south-kingsville' },
            { title: 'South Melbourne', slug: 'south-melbourne' },
            { title: 'South Morang', slug: 'south-morang' },
            { title: 'South Wharf', slug: 'south-wharf' },
            { title: 'South Yarra', slug: 'south-yarra' },
            { title: 'Southbank', slug: 'southbank' },
            { title: 'Spotswood', slug: 'spotswood' },
            { title: 'Springvale', slug: 'springvale' },
            { title: 'Springvale South', slug: 'springvale-south' },
            { title: 'St Albans', slug: 'st-albans' },
            { title: 'St Andrews Beach', slug: 'st-andrews-beach' },
            { title: 'St Helena', slug: 'st-helena' },
            { title: 'St Kilda', slug: 'st-kilda' },
            { title: 'St Kilda East', slug: 'st-kilda-east' },
            { title: 'St Kilda West', slug: 'st-kilda-west' },
            { title: 'Strathmore', slug: 'strathmore' },
            { title: 'Strathmore Heights', slug: 'strathmore-heights' },
            { title: 'Sunshine', slug: 'sunshine' },
            { title: 'Sunshine North', slug: 'sunshine-north' },
            { title: 'Sunshine West', slug: 'sunshine-west' },
            { title: 'Surrey Hills', slug: 'surrey-hills' },
            { title: 'Sydenham VIC', slug: 'sydenham' },
            { title: 'Taylors Hill', slug: 'taylors-hill' },
            { title: 'Taylors Lakes', slug: 'taylors-lakes' },
            { title: 'Tecoma', slug: 'tecoma' },
            { title: 'Templestowe', slug: 'templestowe' },
            { title: 'Templestowe Lower', slug: 'templestowe-lower' },
            { title: 'The Basin', slug: 'the-basin' },
            { title: 'The Patch', slug: 'the-patch' },
            { title: 'Thomastown', slug: 'thomastown' },
            { title: 'Thornbury', slug: 'thornbury' },
            { title: 'Toorak', slug: 'toorak' },
            { title: 'Tootgarook', slug: 'tootgarook' },
            { title: 'Tottenham', slug: 'tottenham' },
            { title: 'Travancore', slug: 'travancore' },
            { title: 'Tremont', slug: 'tremont' },
            { title: 'Truganina', slug: 'truganina' },
            { title: 'Tullamarine', slug: 'tullamarine' },
            { title: 'Tyabb', slug: 'tyabb' },
            { title: 'Upper Ferntree Gully', slug: 'upper-ferntree-gully' },
            { title: 'Upwey', slug: 'upwey' },
            { title: 'Vermont', slug: 'vermont' },
            { title: 'Vermont South', slug: 'vermont-south' },
            { title: 'Viewbank', slug: 'viewbank' },
            { title: 'Wandin North', slug: 'wandin-north' },
            { title: 'Wantirna', slug: 'wantirna' },
            { title: 'Wantirna South', slug: 'wantirna-south' },
            { title: 'Warrandyte', slug: 'warrandyte' },
            { title: 'Warranwood', slug: 'warranwood' },
            { title: 'Waterways', slug: 'waterways' },
            { title: 'Watsonia', slug: 'watsonia' },
            { title: 'Watsonia North', slug: 'watsonia-north' },
            { title: 'Werribee', slug: 'werribee' },
            { title: 'West Footscray', slug: 'west-footscray' },
            { title: 'West Melbourne', slug: 'west-melbourne' },
            { title: 'Westmeadows', slug: 'westmeadows' },
            { title: 'Wheelers Hill', slug: 'wheelers-hill' },
            { title: 'Williams Landing', slug: 'williams-landing' },
            { title: 'Williamstown', slug: 'williamstown' },
            { title: 'Williamstown North', slug: 'williamstown-north' },
            { title: 'Windsor VIC', slug: 'windsor' },
            { title: 'Wyndham Vale', slug: 'wyndham-vale' },
            { title: 'Yallambie', slug: 'yallambie' },
            { title: 'Yarraville', slug: 'yarraville' },
        ],
    },
];
